// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Dok6SPJcKksC6nAL9blvHUQe6lgjqcQ',
    appId: '1:793060189027:web:81ea1e8af9dfb50436a956',
    messagingSenderId: '793060189027',
    projectId: 'medication-tracker-9bb14',
    authDomain: 'medication-tracker-9bb14.firebaseapp.com',
    storageBucket: 'medication-tracker-9bb14.firebasestorage.app',
    measurementId: 'G-4J97EC78V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSAiKXTUwk-8dCJRbwUEMMAFViefiyVMs',
    appId: '1:793060189027:android:07612baa9fcc08bd36a956',
    messagingSenderId: '793060189027',
    projectId: 'medication-tracker-9bb14',
    storageBucket: 'medication-tracker-9bb14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvf_d0V7mVVbXLZIoy1NI_MDPQ578SznE',
    appId: '1:793060189027:ios:1100439d9f38b55136a956',
    messagingSenderId: '793060189027',
    projectId: 'medication-tracker-9bb14',
    storageBucket: 'medication-tracker-9bb14.firebasestorage.app',
    iosBundleId: 'com.example.medicationTracker',
  );
}
